name = "upgrade-meta-to-redirect"
main = "src/worker.js"
workers_dev = true
compatibility_date = "2024-01-22"

[observability]
enabled = false

  [observability.logs]
  enabled = true
  head_sampling_rate = 1
  invocation_logs = true
